// soft-sme-backend/Aiven.ai/AI SQL bot/multi-agent-postgres-data-analytics-main/fe-clients/svelte-ts/src/App.svelte
<!-- code: add a enter key event that takes the 'prompt' and makes a http post request to localhost:3000/prompt using fetch. Take the json response and push it into the 'promptResults' list. Make sure to json.parse the response.results' it will be a json string.  -->

<script lang="ts">
  import svelteLogo from "./assets/svelte.svg";
  import viteLogo from "/vite.svg";

  let prompt: string = "";
  type PromptResult = {
    prompt: string;
    results: Record<string, any>[];
    sql?: string;
  };

  // code: load this from local storage or default to empty list
  let promptResults: PromptResult[] = JSON.parse(localStorage.getItem('promptResults') || '[]');

  async function handleKeyDown(event: KeyboardEvent) {
    if (event.key === "Enter") {
      try {
        const response = await fetch("http://localhost:3000/prompt", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ prompt }),
        });
        if (!response.ok) {
          throw new Error(`HTTP error! status: ${response.status}`);
        }
        const data = await response.json();
        promptResults = [...promptResults, {
          prompt,
          results: JSON.parse(data.results),
          sql: data.sql,
        }];
        localStorage.setItem('promptResults', JSON.stringify(promptResults));
        // code: save promptResults to local storage
        prompt = ""; // Clear the prompt input after submission
      } catch (error) {
        console.error("Error fetching prompt results:", error);
      }
    }
  }
</script>

<main>
  <div>
    <a href="https://vitejs.dev" target="_blank" rel="noreferrer">
      <img src={viteLogo} class="logo" alt="Vite Logo" />
    </a>
    <a href="https://svelte.dev" target="_blank" rel="noreferrer">
      <img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />
    </a>
  </div>
  <h1>Framework: Svelete-TS</h1>
  <h2>TTYDB Prototype</h2>
  <input
    type="text"
    bind:value={prompt}
    placeholder="Enter your prompt"
    on:keydown={handleKeyDown}
  />

  {#each promptResults as result (result.prompt)}
    <section>
      <h3>{result.prompt}</h3>
      <pre>{JSON.stringify(result.results, null, 2)}</pre>
      {#if result.sql}
        <code>{result.sql}</code>
      {/if}
    </section>
  {/each}
</main>

<style>
  .logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
    transition: filter 300ms;
  }

  input,
  button,
  pre,
  section,
  code {
    background-color: #333;
    color: white;
    border: none;
    padding: 0.5em;
    margin: 0.5em 0;
  }

  input,
  button {
    font-size: 1rem;
  }

  pre,
  code {
    font-family: monospace;
  }
</style>

// soft-sme-backend/Aiven.ai/AI SQL bot/multi-agent-postgres-data-analytics-main/fe-clients/vue-ts/src/App.vue
<template>
  <div>
    <a href="https://vitejs.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
    <a href="https://talktoyourdatabase.com" target="_blank">
      <img src="./assets/ttydb.svg" class="logo ttydb" alt="TTYDB logo" />
    </a>
    <h2>Talk To Your Database (Prototype)</h2>
    <h3>Framework: Vue-TS</h3>

    <input
      type="text"
      v-model="prompt"
      :disabled="loading"
      placeholder="Enter your prompt"
      @keyup.enter="sendPrompt"
    />

    <section v-for="(result, index) in sortedPromptResults" :key="index">
      <h3>{{ result.prompt }}</h3>
      <pre>{{ JSON.stringify(result.results, null, 2) }}</pre>
      <code v-if="result.sql">{{ result.sql }}</code>
    </section>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";

import { computed } from "vue";

interface PromptResult {
  prompt: string;
  results: Record<string, any>[];
  sql?: string;
  created: number; // Timestamp for the created date
}

// Computed property to sort prompt results by created date
const sortedPromptResults = computed(() => {
  return [...promptResults.value].sort((a, b) => b.created - a.created);
});

const prompt = ref("");
const loading = ref(false); // Define the loading variable

// code: load this from local storage or default to empty list
const promptResults = ref<PromptResult[]>(
  JSON.parse(localStorage.getItem("promptResults") || "[]")
);

const sendPrompt = async () => {
  loading.value = true; // Start loading
  if (prompt.value.trim() === "") return;
  try {
    const response = await fetch("http://localhost:3000/prompt", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ prompt: prompt.value }),
    });
    if (!response.ok) throw new Error("Network response was not ok");
    const data: any = await response.json();
    const parsed: PromptResult = {
      prompt: data.prompt,
      results: JSON.parse(data.results),
      created: Date.now(),
    };
    if (data.sql) parsed.sql = data.sql;
    promptResults.value.push(parsed);
    localStorage.setItem("promptResults", JSON.stringify(promptResults.value));
    // code: save this to local storage
    prompt.value = ""; // Clear the prompt input after submission
  } catch (error) {
    console.error("There was a problem with the fetch operation:", error);
  } finally {
    loading.value = false; // Stop loading
  }
};
</script>

<style scoped>
.logo {
  background-color: #000000; /* Black background */
}
input,
button,
pre,
section,
code {
  background-color: #1e1e1e;
  color: #ffffff; /* White text */
  border: none;
}

input {
  width: 300px; /* Set the width of the input */
  padding: 0.5em 1em;
  text-align: center;
  margin-bottom: 1em; /* Add space below the input */
}

button {
  padding: 0.5em 1em;
  text-align: center;
}

pre {
  overflow: auto;
  max-height: 200px;
}

section {
  display: flex;
  flex-direction: column;
  gap: 1.5em; /* Increased gap for more space between rows */
  padding: 1em;
}

/* Existing styles */
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}

/* New styles for the TTYDB logo */
.logo.ttydb {
  height: 6em; /* Adjust the size as needed */
}

input:disabled {
  background-color: #1e1e1e;
  color: #ffffff;
  opacity: 0.5;
}
</style>
